server:
  port: 80

spring:
  application:
    name: hystrix-feign-service

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lml.entity
eureka:
  client:
    register-with-eureka: false     #是否向注册中心注册自己
    fetch-registry: true     #是否检索服务。（该服务为注册中心，不需要去检索服务）。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
ribbon:
  ReadTimeout: 5000 #指建立连接所用的时间，适用于网络状况正常情况下，两端连接所用的时间
  ConnectionTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所使用的时间
logging:
  level:
    com.lml.service.PaymentFeign: debug