server:
  port: 80

spring:
  application:
    name: consumer-service


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lml.entity
eureka:
  client:
    #是否向注册中心注册自己
    register-with-eureka: true
    #是否检索服务。（该服务为注册中心，不需要去检索服务）。
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
